### ISSUE TITLE
Async API Requests Communication Issue

### ISSUE THREAD

**Issue by imSarfaroz** [ZhaofengWu/counterfactual-evaluation#1]
There appears to be an issue with the API call. When attempting async requests, it enters an indefinite loop and fails to generate any results. Interestingly, it functions correctly without async requests. Your assistance in investigating this matter would be greatly appreciated. Testing was conducted on an arithmetic dataset.

**Comment by ZhaofengWu** [comment]
Hm interesting, we haven't observed that. It's hard to debug it without more information. Depending on how many instances you want to query, it might be fine to do it asynchronously, but it'll be quite a bit slower.

**Comment by imSarfaroz** [comment]
Yes, I figured it out. It was a problem on my side. It is indeed slower, but for general tests, it is fine.
