### ISSUE TITLE
Missing files prompts.py under syntax/

### ISSUE THREAD

**Issue by vivian1993** [ZhaofengWu/counterfactual-evaluation#3]
Hi,

I appreciate the excellent work you've done! However, I encountered an error while executing syntax/query.py. Here's the error log:

Traceback (most recent call last):
  File "/Users/Documents/counterfactual-evaluation/syntax/query.py", line 10, in <module>
    from prompts import prompt_templates
ModuleNotFoundError: No module named 'prompts'

It looks like this issue may be due to the absence of the prompts.py file. Thank you.

**Comment by ZhaofengWu** [comment]
Thanks for catching this! We just added this file.
